package org.dergigi.ants

internal data class SearchExample(val query: String, val needsLogin: Boolean)

// Existing Android examples plus supported examples from web ants/src/lib/examples.ts.
// Include grouped expressions supported by the shared ANTLR grammar.
internal val searchExamples = listOf(
    // Commands
    "/help",

    // Plain text, phrases, hashtags, and URLs
    "vibe coding",
    "nicolas-cage.gif",
    "nevent",
    "giphy.gif",
    "Gregzaj1-ln_strike.gif",
    "Liotta .gif",
    "\"proof of work\"",
    "#asknostr",
    "#photography",
    "#SovEng",
    "https://dergigi.com/vew",
    "#PenisButter",
    "#YESTR",
    "#gratefulchain",
    "#artstr",

    // Single filters
    "by:dergigi",
    "by:fiatjaf",
    "by:@dergigi.com",
    "p:fiatjaf",
    "p:ants.sh",
    "p:RSS",
    "by:@me",
    "mentions:@me",
    "by:@contacts",
    "mentions:@contacts",
    "has:image",
    "has:video",
    "is:image",
    "is:video",
    "is:media",
    "site:yt",
    "site:github.com",
    "is:highlight",
    "is:code",
    "by:gigi",
    "by:pablof7z",
    "by:corndalorian",
    "by:snowden",
    "by:socrates",
    "until:2023-01-01",
    "p:hodl",
    "p:dergigi.com",
    "p:zaps.lol",
    "p:nostrplebs.com",
    "p:dave",
    "p:edward",
    "p:platobot@dergigi.com",
    "p:twentyone.world",
    "by:dergigi.com",
    "is:file",
    "by:npub1dergggklka99wwrs92yz8wdjs952h2ux2ha2ed598ngwu9w7a6fsh9xzpc",

    "kind:3",
    "kind:10002",

    // Combined filters and text
    "GM by:dergigi",
    "#YESTR by:dergigi",
    "knowledge by:platobot@dergigi.com",
    "GM by:@me",
    "Bitcoin has:image",
    "is:highlight \"proof of work\"",
    "is:article bitcoin",
    "ants since:2w",
    "nostr until:3d",
    "good by:socrates",
    "engineering by:lyn",
    "≠ by:dergigi.com",
    "👀 by:dergigi",
    "NIP-EE by:jeffg",
    ".jpg by:corndalorian",
    "ai site:news.ycombinator.com",
    "by:rektbot 💀💀💀💀💀💀💀💀💀💀",
    "\"car crash\" by:dergigi",
    "free by:ulbricht",
    "\"GM PV\" by:derek",
    "free by:ross",
    "freedom by:ulbricht",
    "bitcoin since:2w",
    "kind:0 #bitcoin",
    "GM has:video",
    "is:image #Olas365",
    "GN by:npub1dergggklka99wwrs92yz8wdjs952h2ux2ha2ed598ngwu9w7a6fsh9xzpc",
    "proof-of-work by:npub1satsv3728d65nenvkmzthrge0aduj8088dvwkxk70rydm407cl4s87sfhu",
    "essay by:npub1sfhflz2msx45rfzjyf5tyj0x35pv4qtq3hh4v2jf8nhrtl79cavsl2ymqt",
    "by:@me has:image",
    "by:dergigi has:image",
    "is:reaction by:dergigi",
    "since:1m until:1w",
    "site:github.com by:fiatjaf",
    "by:dergigi site:yt",
    "by:dergigi until:2026-12-31",
    "by:HODL has:video",
    "is:code by:🌶️",
    "is:code by:hzrd149",
    "is:highlight by:dergigi",
    "is:longform by:dergigi",
    "is:article by:@contacts",
    "GM fiat by:fiatjaf",
    "stay humble by:odell",
    "GM by:dergigi since:12h",
    "hello since:2021-01-01 until:2021-12-31",
    "GM by:dergigi until:2024-06-06",
    "GN by:dergigi since:2025-10-31",
    "by:fiatjaf since:2024-01-01 until:2024-03-31",
    "GM by:dergigi since:2024-01-01 until:2024-03-31",

    // OR alternatives, from short to longer combinations
    "bitcoin OR lightning",
    "PV or 🤙",
    "#plebchain or #introductions",
    "#penisbutter or #⭕️",
    "einundzwanzig or by:twentyone.world",
    "kind:0 OR kind:1",
    "is:image or is:highlight",
    "p:NewsBot OR p:RSS",
    "has:image OR is:image",
    "#pugstr OR #horsestr OR #goatstr",
    "#runstr OR #plebwalk OR by:bitcoinwalk",
    "p:dad OR p:husband OR p:father",
    "🧘‍♀️ or 🧘‍♂️ or 🧘 or 💆",
    "😂 or 🤣 or lol or lmao",
    "PoW by:dergigi OR WoT by:dergigi",
    "nostr by:snowden OR 🫂 by:snowden",
    "is:highlight bitcoin OR is:highlight nostr",
    "is:highlight by:fiatjaf.com OR is:highlight by:@f7z.io",
    "NIP-EE by:jeffg OR NIP-EE by:futurepaul OR NIP-EE by:franzap",
    "GM by:dergigi has:image OR GN by:dergigi has:image",
    "#yestr by:dergigi OR #nostr by:dergigi OR #yestr by:IntuitiveGuy OR #nostr by:IntuitiveGuy",

    // Grouped and scoped expressions
    "(GM OR 🫂) by:dergigi since:2w",
    "(bitcoin OR lightning) by:dergigi",
    "since:2w (bitcoin OR nostr)",
    "(by:dergigi kind:1) OR (by:fiatjaf kind:30023)",
    "by:(dergigi OR fiatjaf) kind:(1 OR 30023)",
    "by:(@me OR @contacts) kind:(1 OR 30023)",
).map { query -> SearchExample(query, needsLogin = Regex("(?i)@(me|contacts)\\b").containsMatchIn(query)) }
    .sortedBy { it.query.length }
