package org.dergigi.ants

internal data class SearchExample(val query: String, val needsLogin: Boolean)

// Existing Android examples plus supported examples from web ants/src/lib/examples.ts.
// Grouped web queries use equivalent complete OR branches; unsupported modifiers
// and event kinds stay out until Android can search and render them.
internal val searchExamples = listOf(
    "vibe coding",
    "bitcoin OR lightning",
    "\"proof of work\"",
    "#asknostr",
    "#photography",
    "#SovEng",
    "#pugstr OR #horsestr OR #goatstr",
    "by:dergigi",
    "by:fiatjaf",
    "by:@dergigi.com",
    "GM by:dergigi",
    "#YESTR by:dergigi",
    "knowledge by:platobot@dergigi.com",
    "p:fiatjaf",
    "p:RSS",
    "by:@me",
    "GM by:@me",
    "mentions:@me",
    "by:@me has:image",
    "has:image",
    "Bitcoin has:image",
    "by:dergigi has:image",
    "has:video",
    "is:image",
    "is:video",
    "is:media",
    "site:yt",
    "site:github.com",
    "https://dergigi.com/vew",
    "is:highlight",
    "is:highlight \"proof of work\"",
    "is:reaction by:dergigi",
    "is:article bitcoin",
    "is:code",
    "kind:0 OR kind:1",
    "ants since:2w",
    "nostr until:3d",
    "GM by:dergigi since:12h",
    "since:1m until:1w",
    "hello since:2021-01-01 until:2021-12-31",
    "GM by:dergigi since:2024-01-01 until:2024-03-31",
    "/help",
    "nicolas-cage.gif",
    "#PenisButter",
    "#YESTR",
    "#gratefulchain",
    "#artstr",
    "nevent",
    "by:gigi",
    "by:pablof7z",
    "by:corndalorian",
    "by:snowden",
    "by:socrates",
    "GM fiat by:fiatjaf",
    "good by:socrates",
    "engineering by:lyn",
    "≠ by:dergigi.com",
    "stay humble by:odell",
    "👀 by:dergigi",
    "NIP-EE by:jeffg",
    ".jpg by:corndalorian",
    "site:github.com by:fiatjaf",
    "by:dergigi site:yt",
    "ai site:news.ycombinator.com",
    "by:rektbot 💀💀💀💀💀💀💀💀💀💀",
    "\"car crash\" by:dergigi",
    "PoW by:dergigi OR WoT by:dergigi",
    "free by:ulbricht",
    "nostr by:snowden OR 🫂 by:snowden",
    "\"GM PV\" by:derek",
    "free by:ross",
    "freedom by:ulbricht",
    "until:2023-01-01",
    "GM by:dergigi until:2024-06-06",
    "GN by:dergigi since:2025-10-31",
    "by:dergigi until:2026-12-31",
    "by:fiatjaf since:2024-01-01 until:2024-03-31",
    "bitcoin since:2w",
    "p:hodl",
    "p:dergigi.com",
    "p:zaps.lol",
    "p:nostrplebs.com",
    "p:dave",
    "p:edward",
    "p:platobot@dergigi.com",
    "p:twentyone.world",
    "kind:0 #bitcoin",
    "PV or 🤙",
    "is:image or is:highlight",
    "🧘‍♀️ or 🧘‍♂️ or 🧘 or 💆",
    "😂 or 🤣 or lol or lmao",
    "#plebchain or #introductions",
    "einundzwanzig or by:twentyone.world",
    "#runstr OR #plebwalk OR by:bitcoinwalk",
    "p:dad OR p:husband OR p:father",
    "GM by:dergigi has:image OR GN by:dergigi has:image",
    "p:NewsBot OR p:RSS",
    "#yestr by:dergigi OR #nostr by:dergigi OR #yestr by:IntuitiveGuy OR #nostr by:IntuitiveGuy",
    "has:image OR is:image",
    "giphy.gif",
    "Gregzaj1-ln_strike.gif",
    "Liotta .gif",
    "GM has:video",
    "by:HODL has:video",
    "is:image #Olas365",
    "by:dergigi.com",
    "is:file",
    "is:code by:🌶️",
    "is:code by:hzrd149",
    "is:highlight by:dergigi",
    "is:highlight bitcoin OR is:highlight nostr",
    "is:highlight by:fiatjaf.com OR is:highlight by:@f7z.io",
    "#penisbutter or #⭕️",
    "is:longform by:dergigi",
    "NIP-EE by:jeffg OR NIP-EE by:futurepaul OR NIP-EE by:franzap",
    "by:npub1dergggklka99wwrs92yz8wdjs952h2ux2ha2ed598ngwu9w7a6fsh9xzpc",
    "GN by:npub1dergggklka99wwrs92yz8wdjs952h2ux2ha2ed598ngwu9w7a6fsh9xzpc",
    "proof-of-work by:npub1satsv3728d65nenvkmzthrge0aduj8088dvwkxk70rydm407cl4s87sfhu",
    "essay by:npub1sfhflz2msx45rfzjyf5tyj0x35pv4qtq3hh4v2jf8nhrtl79cavsl2ymqt",
).map { query -> SearchExample(query, needsLogin = query.contains(":@me")) }
